### ISSUE TITLE
Add rejected apps/templates from awesome-flutter

### ISSUE THREAD

**Issue by rayliverified** [jogboms/awesome-flutter-showcase#2]
awesome-flutter has rejected a lot of interesting Flutter applications. Why not add them here?

**Comment by jogboms** [comment]
Yeah. 
That's the motivation really. I watch the #awesome-flutter repo and see many beautiful examples and starter projects get rejected almost on a daily. 
The plan is to populate here as much as I can for others to find as well. Help out if you can, I kinda have a tight schedule at work.
